### ISSUE TITLE
Refactor grid printing logic and loop (with min and max coordinates) to shared code

### ISSUE THREAD

**Issue by obijywk** [obijywk/grilops#4]

**Comment by jaylorch** [comment]
My next plan is to replace the location set (which is currently passed in as just a list of points) with an abstract Grid class. This way, using subclasses RectangularGrid, FlatToppedHexGrid, and PointyToppedHexGrid, it would represent a not-necessarily-rectangular grid. The idea is that the Grid would have its own methods for adjacency, rotation, etc. So that seems like a good place to put the print routine to fix this issue.
